[selene]
base = "lua51"
name = "neovim"

[vim]
any = true

[[assert.args]]
type = "bool"

[[assert.args]]
type = "string"
required = false

[[assert.is_nil.args]]
type = "any"

[[assert.is_not_nil.args]]
type = "any"

[assert.matches]
any = true

[assert.has_error]
any = true

[assert.are]
any = true

[[assert.equals.args]]
type = "any"
[[assert.equals.args]]
type = "any"
[[assert.equals.args]]
type = "any"
required = false

[[assert.same.args]]
type = "any"
[[assert.same.args]]
type = "any"

[[assert.truthy.args]]
type = "any"

[[assert.falsy.args]]
type = "any"

[[assert.spy.args]]
type = "any"

[[assert.stub.args]]
type = "any"


[[after_each.args]]
type = "function"

[[before_each.args]]
type = "function"

[[describe.args]]
type = "string"

[[describe.args]]
type = "function"

[[it.args]]
type = "string"

[[it.args]]
type = "function"

[[setup.args]]
type = "function"
